### ISSUE TITLE
Nothing inside main of 83th solution.

### ISSUE THREAD

**Issue by Udhay-Brahmi** [ndkaur/leetcode#4]
Please improve it.
By the way repo. is good.

**Comment by Udhay-Brahmi** [comment]
[https://github.com/ndkaur/leetcode/blob/master/83.remove-duplicates-from-sorted-list.cpp](url)

**Comment by ndkaur** [comment]
It's a linked list question . For writing int he main function for linked list first you need to convert list into array then proceed . 
but leetcode itself has int main included . So i just wanted to check if the solution works or not , that's why i haven't made main( ).
